#!/usr/bin/env bash
# Sync Tool (stl)
#

#CONFIGURE ME everything that you want to exclude from the diffs:
if [[ $1 == "install" ]]; then
    chmod +x ~/bin/stl 
    cd ~/bin 
    rm -rf stl-*
    ln -s stl stl-vim 
    ln -s stl stl-check 
    ln -s stl stl-sync
    ln -s stl stl-diff
    ln -s stl stl-check-full
    ln -s stl stl-sync-full
    exit 0
fi

exclusions=$(cat << EOF
"installation/src"
"installation/develop*"
"installation/*eggs"
"installation/bin"
"staging"
"parts"
".installed.cfg"
".DS_Store"
".git"
"*.pyc"
"*.pyo"
"*.class"
"*.ear"
"*.war"
"target"
".settings"
".*"
EOF
)
# END configuration part

me=`basename "$0"`

if [[ $# -lt 2 ]]; then
    cat << EOF
    usage $0 source destination (only one remote)    
EOF
  exit 1
fi

if [[ "$1" =~ ":" ]] &&  [[ "$2" =~ ":" ]] 
then
    echo "cannot operate with 2 remotes"
    exit 1
fi



SOURCE=$1
DESTINATION=$2

if [[ "$SOURCE" =~ ":" ]]; then
    REMOTE=$SOURCE
fi

if [[ "$DESTINATION" =~ ":" ]]; then
    REMOTE=$DESTINATION
fi


if [[ $me == "stl-check" ]]; then
    for a in $exclusions
        do  
            echo "$a"
        done | xargs -I{} echo "--exclude" \"{}\"  | xargs rsync -navhz $SOURCE $DESTINATION --delete --no-perms --no-owner --no-group --checksum --out-format="%i %B %o %U %n" 
    exit 0
fi

if [[ $me == "stl-sync" ]]; then
    for a in $exclusions
        do  
            echo "$a"
        done | xargs -I{} echo "--exclude" \"{}\"  | xargs rsync -avhz $SOURCE $DESTINATION --delete --no-perms --no-owner --no-group --checksum --out-format="%i %B %o %U %n" 
    exit 0
fi

if [[ $me == "stl-check-full" ]]; then
rsync -navhz $SOURCE $DESTINATION --delete --no-perms --no-owner --no-group --checksum --out-format="%i %B %o %U %n" 
fi

if [[ $me == "stl-sync-full" ]]; then
rsync -avhz $SOURCE $DESTINATION --delete --no-perms --no-owner --no-group --checksum --out-format="%i %B %o %U %n" 
fi


for a in $exclusions 
do 
    echo "$a"
done | xargs -I{} echo "--exclude" \"{}\"  | xargs rsync -navhz $SOURCE $DESTINATION --delete --no-perms --no-owner --no-group --checksum --out-format="%i %B %o %U %n"  |  while read line 
    do
      linesquid=$(echo ${line} | grep -v "+++++++" | grep -e '^<' -e '^>'  )
      if [[ $? != 0 ]]; then
          continue
      fi
      filepath=$(echo $linesquid | awk '{print $5}')
      if [[ $me == "stl-vim" ]]; then
          VIMDIFF_PATH=$(echo $REMOTE | awk -F ':' '{print "scp://"$1"/"$2}')
          if [[ $DESTINATION == $REMOTE ]] ; then
              test -f "$filepath" && vimdiff ${filepath} ${VIMDIFF_PATH}${filepath} < /dev/tty
          else
              test -f "$filepath" && vimdiff ${VIMDIFF_PATH}${filepath} ${filepath} < /dev/tty
          fi

      elif [[ $me == "stl-diff" ]]; then
        HOST_PART=$(echo $REMOTE | awk -F ':' '{print $1}')
        PATH_PART=$(echo $REMOTE | awk -F ':' '{print $2}')
        if [[ $DESTINATION == $REMOTE ]] ; then
            ssh $HOST_PART cat ${PATH_PART}${filepath} < /dev/tty | colordiff -u $filepath -
        else
            ssh $HOST_PART cat ${PATH_PART}${filepath} < /dev/tty | colordiff -u - $filepath
        fi
      else
         test -f "$filepath" && echo ${line}
      fi
    done 



